### PR TITLE
Add docstring for '*' variants of functions.

### PR DESCRIPTION
**Pull request by crocket**

### CODE REVIEW

**Comment by sogaiu** [comment]
Nice!  Especially the short examples.

Below are some additional observations.

* I noticed that the docstrings use the word "array", but the examples seem to be using tuples.  May be that could be confusing?

* Perhaps the docstrings of the macro versions could use similar examples as IIUC they are possibly more likely to be used than the functions versions.  I'm willing to do this if having examples is acceptable.

* How about using the word "function" instead of "non-macro" in the docstrings?

**Comment by andrewchambers** [comment]
thanks! I really appreciate this work.

**Comment by crocket** [comment]
@sogaiu You are welcome to submit more pull requests. I used array as a plain english word because I didn't like the word, tuple.

**Comment by sogaiu** [comment]
@crocket Thanks for the explanation (and submitting the original PR).

I will consider an additional PR.

**Pull request merged**
